# Generated by Django 4.2.2 on 2025-07-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Dashboard', '0002_vault_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts.loginmodel'),
        ),
    ]
