# Generated by Django 4.2.2 on 2025-07-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_vault_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
