# Generated by Django 4.2.2 on 2025-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_delete_abc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter (X)', 'Twitter (X)'), ('LinkedIn', 'LinkedIn'), ('Snapchat', 'Snapchat'), ('Pinterest', 'Pinterest'), ('Reddit', 'Reddit'), ('Quora', 'Quora'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp'), ('Discord', 'Discord'), ('GitHub', 'GitHub'), ('GitLab', 'GitLab'), ('Bitbucket', 'Bitbucket'), ('Gmail', 'Gmail'), ('Yahoo Mail', 'Yahoo Mail'), ('Outlook', 'Outlook'), ('ProtonMail', 'ProtonMail'), ('Zoho Mail', 'Zoho Mail'), ('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('Myntra', 'Myntra'), ('Snapdeal', 'Snapdeal'), ('Netflix', 'Netflix'), ('Hotstar (Disney+)', 'Hotstar (Disney+)'), ('Spotify', 'Spotify'), ('Zoom', 'Zoom'), ('Slack', 'Slack'), ('Medium', 'Medium')], max_length=100),
        ),
    ]
