# Generated by Django 4.2.2 on 2025-07-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='user',
        ),
    ]
