# Generated by Django 4.2.2 on 2025-07-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_vault_user'),
        ('Accounts', '0002_remove_loginmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
