# Generated by Django 4.2.2 on 2025-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_delete_loginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
