# Generated by Django 4.2.2 on 2025-07-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_signupmodel_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='pin',
            field=models.CharField(max_length=8),
        ),
    ]
